# Generated by Selenium IDE
import pytest
import json
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from .utils import get_timestamp, teardown_driver  # Removed unused imports
from .login import Login
from .fna_helper import FNAHelpers  # Import FNAHelpers


class FNA:

    def perform_fna(self, env_id, login_id):  # Add 'self' as the first parameter
        # Perform login operation and get driver
        # Pass env_Id and login_id to perform_login
        driver = Login.perform_login(env_id, login_id)

        try:
            # Wait for the ion-backdrop to disappear and click financial analysis button
            FNAHelpers.start_new_fna(driver)

            # Set marital status using helper method
            FNAHelpers.set_marital_status(
                driver,
                "widowed"
            )

            # Input number of dependents using helper method
            FNAHelpers.set_number_of_dependents(
                driver, "1-3"
            )

            # Input family name and given name using helper method
            FNAHelpers.input_english_name(driver, "Lee", "Three")

            # Input mobile number using helper method
            # FNAHelpers.input_mobile_number(driver, "98763456")

        except Exception as e:
            print(f"\nERROR: An error occurred - {str(e)}\n")
            raise
        finally:
            teardown_driver(driver)
